Use message type instead of prototype
confluentinc/confluent-kafka-python pull request #1407
Opened 2022-08-14 16:41 UTC by 0x26res

I've fixed the issue and added some tests. 

But I wasn't reproduce the issue with this repo set up. The issue stems from the fact that in some environment:
```
MessageFactory().GetPrototype(message_type.DESCRIPTOR) is not messsage_type
```

I think it must have something to do with a different combination of `protoc` and `protobuf` python library.

Does anyone happen to know what version of `protoc` has been used to generate the pb2.py files?

Thanks.

2022-08-14 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/confluentinc/confluent-kafka-python?pullRequest=1407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/confluentinc/confluent-kafka-python?pullRequest=1407) before we can accept your contribution.<br/><hr/>**0x26res** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/confluentinc/confluent-kafka-python?pullRequest=1407) it.</sub>

2022-08-25 17:56 UTC, pranavrth requested changes
Please fix the build issues. Mostly related to the styling. 

https://app.travis-ci.com/github/confluentinc/confluent-kafka-python/builds/254834885#L827

2022-08-25 17:56 UTC, pranavrth commented on tests/integration/schema_registry/test_proto_serializers.py
> +from tests.schema_registry.test_proto import TEST_DATA
It's better to keep data in their respective test files. Its fine here to replicate data in each file if we require that.

2022-08-25 17:56 UTC, pranavrth commented on tests/schema_registry/test_proto.py
> +TEST_DATA = [
No need for such complex data while testing our usecase. Keep only what is really required.

Move data near the testcase.

2022-08-25 17:56 UTC, pranavrth commented on tests/integration/schema_registry/test_proto_serializers.py
> -
Keep this extra line. Each test is separated by 2 lines.

2022-08-25 17:56 UTC, pranavrth commented on src/confluent_kafka/schema_registry/protobuf.py
> +
Remove this extra line.

2022-08-25 17:56 UTC, pranavrth commented on tests/schema_registry/test_proto.py
> +def test_round_trip(mock_schema_registry, pb2, data):
Please write a better name for the test which suggests what we are trying to test. Something in the line of serializing, deserializing and then again serializing. Better to have verbose test name.

2022-08-25 17:56 UTC, pranavrth commented on tests/schema_registry/test_proto.py
> +    assert isinstance(message_after, pb2)
Keep all asserts continuously.

Add a line break before assert.

2022-08-25 17:56 UTC, pranavrth commented on tests/schema_registry/test_proto.py
> +def test_foo_bar():
We are removing this code altogether, so I think we don't need to test this. Please remove this function.

2022-09-01 16:54 UTC, 0x26res commented
@pranavrth thanks for the feed back. I've addressed the comments.

The CI is failing, but (unless I'm mistaken) I think the serdes branch has been left in a bad state, some tests need fixing.

2022-09-05 14:52 UTC, pranavrth commented
Hello @0x26res,

The testcases related to protobuf were failing in **serdes** branch. I have fixed and merged the test cases. Please resolve the conflict and it should work fine.

2022-09-06 18:41 UTC, 0x26res commented
@pranavrth thanks for fixing, it looks good now.

2022-09-07 10:49 UTC, pranavrth commented
LGTM

2022-09-07 10:50 UTC, pranavrth approved these changes

2022-09-07 17:15 UTC, 0x26res commented
@pranavrth I don't have write access so I won't be able to merge. Can I leave this to you? Thanks

2022-09-14 21:45 UTC, closed without merging

2022-09-16 16:53 UTC, 0x26res commented
@mhowlett is that not going through? Should I send another MR?